import json
from typing import Optional
from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from app.dependencies import get_current_user
from app.auth.jwt_handler import UserContext
from app.agent.graph import run_agent

router = APIRouter(prefix="/api/chat", tags=["chat"])

class ChatRequest(BaseModel):
    message: str
    conversation_id: Optional[str] = "default"

@router.post("")
async def chat_endpoint(request: ChatRequest, user: UserContext = Depends(get_current_user)):
    """
    Main entry point for the Agentic RAG chat.
    Uses Server-Sent Events (SSE) to stream back the agent's progress, tool calls, and final answer.
    """
    async def event_generator():
        try:
            # We iterate over the stream of events from the LangGraph agent
            async for event in run_agent(request.message, user.user_id, user.role, request.conversation_id):
                kind = event["event"]
                
                # We can stream tokens as they are generated by the LLM
                if kind == "on_chat_model_stream":
                    content = event["data"]["chunk"].content
                    if content:
                        yield f"data: {json.dumps({'type': 'token', 'content': content})}\n\n"
                        
                # We can notify the frontend when tools are being called
                elif kind == "on_tool_start":
                    tool_name = event["name"]
                    yield f"data: {json.dumps({'type': 'tool_start', 'tool': tool_name})}\n\n"
                    
                # And finally, the complete state updates from the graph nodes
                elif kind == "on_chain_end" and event["name"] == "agent":
                    # This is the final state of the graph
                    final_state = event["data"]["output"]
                    yield f"data: {json.dumps({'type': 'final_state', 'state': final_state})}\n\n"
                    
        except Exception as e:
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"
            
    return StreamingResponse(event_generator(), media_type="text/event-stream")
